# Generated by Django 4.2.3 on 2023-09-25 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('G20', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Title',
            new_name='Topic',
        ),
    ]
