# Generated by Django 4.2.3 on 2023-09-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('G20', '0002_rename_title_item_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='topic_type',
            field=models.CharField(choices=[('key_features', 'Key Features'), ('topics', 'Topics Of Discussion'), ('people', 'Guests')], default='Key Features', max_length=200),
        ),
    ]
