# Generated by Django 4.2.3 on 2023-09-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('G20', '0003_item_topic_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='', upload_to='G20/images'),
        ),
    ]
